# Generated by Django 3.0.6 on 2020-06-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0004_auto_20200618_1223'),
        ('testgenre', '0002_auto_20200611_1936'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bookapp-pics', verbose_name='Фото книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('authors', models.ManyToManyField(to='authors.Authors', verbose_name='Автор книги')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testgenre.Genre', verbose_name='Жанр книги')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publisher.Publisher', verbose_name='Автор книги')),
            ],
        ),
    ]
