# Generated by Django 3.0.6 on 2020-06-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookapp',
            name='authors',
        ),
        migrations.AddField(
            model_name='bookapp',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authors.Authors', verbose_name='Автор книги'),
            preserve_default=False,
        ),
    ]
