# Generated by Django 3.0.6 on 2020-07-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200618_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapp',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookapp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookapp',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
