# Generated by Django 3.0.6 on 2020-07-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testgenre', '0002_auto_20200611_1936'),
        ('publisher', '0004_auto_20200618_1223'),
        ('authors', '0001_initial'),
        ('book', '0006_bookapp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapp',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_book', to='authors.Authors', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='bookapp',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_book', to='testgenre.Genre', verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='bookapp',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_book', to='publisher.Publisher', verbose_name='Издательство'),
        ),
    ]
