# Generated by Django 3.0.6 on 2020-07-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200701_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles-pics', verbose_name='Фото пользователя'),
        ),
    ]
