# Generated by Django 3.0.6 on 2020-08-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200701_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='address1',
            field=models.CharField(default=111, max_length=500, verbose_name='Адрес доставки основной'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='address2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки дополнительный'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.EmailField(default=111, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(default=111, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(default=111, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='password',
            field=models.CharField(default=111, max_length=15, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='phone_number',
            field=models.IntegerField(default=111, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(default=111, max_length=15, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
