# Generated by Django 3.0.6 on 2020-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=10, verbose_name='IP')),
                ('name', models.CharField(max_length=16, verbose_name='Браузер')),
                ('description', models.TextField(verbose_name='Полный запрос')),
            ],
        ),
    ]
