# Generated by Django 3.0.6 on 2020-06-03 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_bd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 3, 21, 20, 11, 615857, tzinfo=utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsing',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
