# Generated by Django 3.0.6 on 2020-06-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название издательства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Аннотация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publisher-pics', verbose_name='Логотип издательства')),
            ],
        ),
    ]
