# Generated by Django 3.0.6 on 2020-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Логотип издательства'),
        ),
    ]
